[package]
name = "buildj"
version = "0.1.4"
authors = ["Hatter Jiang <jht5945@gmail.com>"]
edition = "2018"

[dependencies]
json = "0.12.4"
term = "0.6.1"
reqwest = "0.9.18"
urlencoding = "1.1.1"
dirs = "3.0.1"
rust-crypto = "0.2.36"
lazy_static = "1.4.0"
rust_util = "0.6.22"
